# version: '3.9'
# services:
#   web:
#     build: .
#     command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     volumes:
#       - .:/app
#     ports:
#       - 3000:3000
#     depends_on:
#       - dynamodb-local
#       - postgresdb
#     tty: true
#     stdin_open: true

#     dynamodb-local:
#     container_name: dynamodb-local
#     image: amazon/dynamodb-local
#     user: root
#     command: -jar DynamoDBLocal.jar -dbPath /db
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./db:/db

#   dynamodb-admin:
#     container_name: dynamodb-admin
#     image: aaronshaf/dynamodb-admin:latest
#     environment:
#       - DYNAMO_ENDPOINT=http://dynamodb-local:8000
#       - AWS_REGION=ap-northeast-1
#       - AWS_ACCESS_KEY_ID=1234567890
#     ports:
#       - 8001:8001
#     depends_on:
#       - dynamodb-local

#     postgresdb:
#     image: postgres:11
#     container_name: wcl.article.postgresql
#     ports:
#       - 5432:5432
#     volumes:
#       - ./tmp/db:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: "django"
#       POSTGRES_PASSWORD: "django1234"
#     hostname: postgresdb
version: "3.9"
services:
  web:
    build: .
    container_name: outline-create-tool-ojt
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
    tty: true
    stdin_open: true

  postgresdb:
    image: postgres:11
    container_name: outline_db_ojt
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "outline_admin"
      POSTGRES_PASSWORD: "outline@admin"
    hostname: postgresdb
